# Generated by Django 3.1.3 on 2020-12-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='department',
    #         fields=[
    #             ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('name', models.CharField(max_length=250)),
    #             ('icon', models.CharField(max_length=250)),
    #         ],
    #     ),
    # ]
