# Generated by Django 3.1.3 on 2020-12-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KFUPMCollection', '0003_answer_contains_course_dep_departments_evaluation_instructor_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('RID', models.CharField(max_length=250)),
                ('Type', models.CharField(max_length=250)),
                ('CID', models.CharField(max_length=250)),
                ('path', models.FileField(upload_to='KFUPMCollection/static/KFUPMCollection/upload ')),
            ],
            options={
                'db_table': 'resource',
            },
        ),
    ]
